module.exports = [
    {
        name: 'listBaremetalServers',
        type: 'baremetal-server',
        path: '/servers/detail',
        method: 'GET',
        key: 'servers',
        payload: null,
    },
    {
        name: 'listBaremetalFlavors',
        type: 'baremetal-server',
        path: '/flavors/detail',
        method: 'GET',
        key: 'flavors',
        payload: null,
    },
    {
        name: 'getBaremetalServer',
        type: 'baremetal-server',
        path: '/servers/:id',
        key: 'server',
        method: 'GET',
        payload: null,
    },
    {
        name: 'deleteBaremetalServer',
        type: 'baremetal-server',
        path: '/servers/:id',
        method: 'DELETE',
        payload: null,
    },
    {
        name: 'getBaremetalConsole',
        type: 'baremetal-server',
        path: '/servers/:id/action',
        method: 'POST',
        key: 'console',
        payload: { 'os-getManagementConsole': null },
    },
    {
        name: 'startBaremetalServer',
        type: 'baremetal-server',
        path: '/servers/:id/action',
        method: 'POST',
        payload: { 'os-start': { boot_mode: 'DISK' } },
    },
    {
        name: 'rebootBaremetalServer',
        type: 'baremetal-server',
        path: '/servers/:id/action',
        method: 'POST',
        payload: {
            reboot: {
                type: 'SOFT',
                boot_mode: 'disk',
            },
        },
    },
    {
        name: 'listBaremetalZones',
        type: 'baremetal-server',
        path: '/os-availability-zone',
        key: 'availabilityZoneInfo',
        method: 'GET',
        payload: null,
    },
    {
        name: 'listBaremetalKeypairs',
        type: 'baremetal-server',
        path: '/os-keypairs',
        key: 'keypairs',
        method: 'GET',
        payload: null,
    },
    {
        name: 'listBaremetalLimits',
        type: 'baremetal-server',
        path: '/limits',
        key: 'limits',
        method: 'GET',
        payload: null,
    },
    {
        name: 'listBaremetalServerMetadata',
        type: 'baremetal-server',
        path: '/servers/:id/metadata',
        key: 'metadata',
        method: 'GET',
        payload: null,
    },
]
