module.exports = [
    {
        name: 'listZones',
        type: 'compute',
        path: '/os-availability-zone',
        key: 'availabilityZoneInfo',
        method: 'GET',
        payload: null,
    },
    {
        name: 'listServers',
        type: 'compute',
        path: '/servers/detail',
        key: 'servers',
        method: 'GET',
        payload: null,
    },
    {
        name: 'getServer',
        type: 'compute',
        path: '/servers/:id',
        key: 'server',
        method: 'GET',
        payload: null,
    },
    {
        name: 'getConsole',
        type: 'compute',
        path: '/servers/:id/action',
        method: 'POST',
        key: 'console',
        payload: { 'os-getVNCConsole': { type: 'novnc' } },
    },
    {
        name: 'startServer',
        type: 'compute',
        path: '/servers/:id/action',
        method: 'POST',
        payload: { 'os-start': null },
    },
    {
        name: 'stopServer',
        type: 'compute',
        path: '/servers/:id/action',
        method: 'POST',
        payload: { 'os-stop': null },
    },
    {
        name: 'resizeServer',
        type: 'compute',
        path: '/servers/:id/action',
        method: 'POST',
    },
    {
        name: 'deleteServer',
        type: 'compute',
        path: '/servers/:id',
        method: 'DELETE',
    },
]
